name: Deploy Next.js predev

on:
  push:
    branches:
      - pre-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on TrueNAS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            incus exec PrePortfolio -- bash -c '
              cd portfolio
              git checkout pre-dev
              git restore package-lock.json
              git pull
              npm install
              npm run build
              export RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}"
              pm2 restart PrePortfolio --update-env
              if [ -n "$RESEND_API_KEY" ]; then echo "RESEND_API_KEY présente"; else echo "RESEND_API_KEY absente"; fi
            '