name: Deploy Next.js predev

on:
  push:
    branches:
      - pre-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on TrueNAS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            incus exec PrePortfolio -- bash
            cd portfolio
            git checkout pre-dev
            git pull
            npm install
            npm run build
            pm2 restart PrePortfolio